## Preprocessing

In [82]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [83]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

# New Section

In [84]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

# Optimization: only drop EIN and keep NAME column
application_df = application_df.drop(['EIN'], axis = 1)

In [85]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [86]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
print(application_df.nunique())

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [88]:
# Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()

# Names counts > 5
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [89]:
names_to_replace = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [90]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [91]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

# Optimization: increased the category types
application_types_to_replace = application_df[application_df['APPLICATION_TYPE'].map(type_counts) < 500]['APPLICATION_TYPE']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [92]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [93]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_counts[classification_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [94]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = application_df[application_df['CLASSIFICATION'].map(application_df['CLASSIFICATION'].value_counts()) <= 1000]['CLASSIFICATION']
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [95]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
# Generate categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
converted_df = pd.get_dummies(application_df)
converted_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [96]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = converted_df['IS_SUCCESSFUL'].values
X = converted_df.drop('IS_SUCCESSFUL', axis = 'columns').values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
# Optimization trial: decreased the test size and increased train size
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [97]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [98]:
X.shape

(34299, 398)

## Compile, Train and Evaluate the Model

In [99]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

#  YOUR CODE GOES HERE

# Optimization: added more hidden layers increased the units
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 100)               39900

 dense_25 (Dense)            (None, 30)                3030

 dense_26 (Dense)            (None, 10)                310

 dense_27 (Dense)            (None, 1)                 11

=================================================================
Total params: 43,251
Trainable params: 43,251
Non-trainable params: 0
_________________________________________________________________

In [100]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

In [101]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4936 - accuracy: 0.7752
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4444 - accuracy: 0.7944
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4360 - accuracy: 0.7964
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4315 - accuracy: 0.7971
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4285 - accuracy: 0.7975
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4268 - accuracy: 0.7968
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4252 - accuracy: 0.7984
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4242 - accuracy: 0.7990
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4227 - accuracy: 0.7996
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4220 - accuracy: 0.8008
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.7995
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4199 - accuracy: 0.8012
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4195 - accuracy: 0.7999
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4185 - accuracy: 0.8012
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4176 - accuracy: 0.8026
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4173 - accuracy: 0.8017
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4165 - accuracy: 0.8022
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4162 - accuracy: 0.8019
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4157 - accuracy: 0.8034
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4150 - accuracy: 0.8028
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4147 - accuracy: 0.8025
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4142 - accuracy: 0.8031
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4138 - accuracy: 0.8034
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4129 - accuracy: 0.8039
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4124 - accuracy: 0.8041
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4122 - accuracy: 0.8042
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4121 - accuracy: 0.8049
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4115 - accuracy: 0.8043
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4109 - accuracy: 0.8051
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4110 - accuracy: 0.8053
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8055
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4102 - accuracy: 0.8047
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4097 - accuracy: 0.8050
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4091 - accuracy: 0.8054
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4089 - accuracy: 0.8054
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4088 - accuracy: 0.8059
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4083 - accuracy: 0.8059
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4079 - accuracy: 0.8056
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4083 - accuracy: 0.8056
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4079 - accuracy: 0.8060
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4081 - accuracy: 0.8067
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4072 - accuracy: 0.8064
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4071 - accuracy: 0.8067
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4068 - accuracy: 0.8067
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4068 - accuracy: 0.8065
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4066 - accuracy: 0.8059
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4060 - accuracy: 0.8079
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8060
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4058 - accuracy: 0.8071
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4056 - accuracy: 0.8064
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4058 - accuracy: 0.8071
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8077
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8073
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8078
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8075
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4050 - accuracy: 0.8075
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4049 - accuracy: 0.8077
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8071
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8073
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4043 - accuracy: 0.8073
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4038 - accuracy: 0.8072
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8073
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4042 - accuracy: 0.8072
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4038 - accuracy: 0.8083
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4037 - accuracy: 0.8084
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4040 - accuracy: 0.8077
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4040 - accuracy: 0.8080
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4035 - accuracy: 0.8086
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8090
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8082
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4035 - accuracy: 0.8084
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4037 - accuracy: 0.8086
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4032 - accuracy: 0.8080
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4030 - accuracy: 0.8085
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4029 - accuracy: 0.8092
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8094
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4029 - accuracy: 0.8090
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4025 - accuracy: 0.8084
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4026 - accuracy: 0.8089
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8088
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4027 - accuracy: 0.8082
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4029 - accuracy: 0.8088
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4025 - accuracy: 0.8082
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4020 - accuracy: 0.8089
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8085
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8082
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4021 - accuracy: 0.8089
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4017 - accuracy: 0.8084
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8085
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4022 - accuracy: 0.8087
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8086
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8090
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4025 - accuracy: 0.8079
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8082
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8088
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4021 - accuracy: 0.8084
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8085
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8080
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8086
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8086

In [102]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4501 - accuracy: 0.7880 - 281ms/epoch - 1ms/step
Loss: 0.4500695466995239, Accuracy: 0.7879883646965027

In [103]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('/content/drive/MyDrive/Colab Notebooks/AlphabetSoupCharity_Optimization.h5')

**Data Preprocessing**

1. What variable(s) are the target(s) for your model?

> The "IS_SUCCESSFUL" column.



2. What variable(s) are the features for your model?
> NAME, APPLICATION, TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT,SPECIAL_CONSIDERATIONS, STATUS, and ASK_AMT

3. What variable(s) should be removed from the input data because they are neither targets nor features?
> EIN (Employer identification) was dropped.



**Compiling, Training, and Evaluating the Model**

1. How many neurons, layers, and activation functions did you select for your neural network model, and why?
> Number of layers: 3; number of neurons: first layer - 100, second layer - 30, third layer - 10. Activation functions: first layer - relu, second and third layer - sigmoid. The reason is that accuracy increased. 

2. Were you able to achieve the target model performance?
> Yes.

3. What steps did you take in your attempts to increase model performance?
> Converting NAME column into data points (impact the most), change activation function to sigmoid for the 2nd and 3rd layer.



**Summary**

Overall, by proper optimization this model achieved the accuracy above 75%. Another model recommended is the Random Forest model, which is good for classification problems.

In [104]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [105]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest model accuracy: 0.776